name: master

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  tests:
    name: unittests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.9, 3.x]
    steps:
      - name: install libxml2-dev
        run: sudo apt-get install libxml2-dev libxslt-dev

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: Install pip/pipenv
        run: pip install -U pip==20.2.3 pipenv==2020.8.13

      - name: pipenv install --dev
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: pipenv run test
        run: pipenv run test

      - name: Coveralls
        if: matrix.python == '3.9'
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: |
          coveralls

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: install {libxml2,libxslt}-dev
        run: sudo apt-get install libxml2-dev libxslt-dev

      - name: checkout
        uses: actions/checkout@v2

      - name: Install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip/pipenv
        run: pip install -U pip==20.2.3 pipenv==2020.8.13

      - name: pipenv install --dev
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: pipenv run lint
        run: pipenv run lint

      - name: pipenv run fmt-check
        run: pipenv run fmt-check

      - name: pipenv run isort-check
        run: pipenv run isort-check
